# Generated by Django 4.2.30 on 2026-07-19 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="file",
            new_name="resume_file",
        ),
        migrations.AddField(
            model_name="resume",
            name="extracted_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="title",
            field=models.CharField(default="Resume", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resume",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_resumes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
