# Generated by Django 6.0.7 on 2026-07-20 04:56

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_emailotp_rename_name_customuser_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=django_mongodb_backend.fields.ObjectIdAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
