# Generated by Django 6.0.7 on 2026-07-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0002_alter_usersettings_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
