import {
  FaRobot,
  FaArrowRight,
  FaLightbulb,
} from "react-icons/fa";

const recommendations = [
  {
    title: "Learn Docker",
    description:
      "Docker is required in nearly 82% of Full Stack job openings.",
  },
  {
    title: "Complete AWS Cloud Practitioner",
    description:
      "Cloud certifications significantly improve hiring chances.",
  },
  {
    title: "Improve System Design",
    description:
      "Essential for Software Engineer & SDE-2 interviews.",
  },
];

function AIRecommendations({ recommendations = [] }) {
  const displayRecommendations = recommendations && recommendations.length > 0
    ? recommendations.map((rec) => ({
        title: rec.startsWith("Add ") ? rec : `Recommendation`,
        description: rec
      }))
    : [
        {
          title: "Learn Docker",
          description:
            "Docker is required in nearly 82% of Full Stack job openings.",
        },
        {
          title: "Complete AWS Cloud Practitioner",
          description:
            "Cloud certifications significantly improve hiring chances.",
        },
        {
          title: "Improve System Design",
          description:
            "Essential for Software Engineer & SDE-2 interviews.",
        },
      ];

  return (
    <div className="bg-white rounded-[32px] border border-slate-200 shadow-sm p-8">

      <div className="flex items-center gap-4 mb-8">

        <div className="w-14 h-14 rounded-2xl bg-blue-50 flex items-center justify-center">
          <FaRobot className="text-blue-600 text-2xl"/>
        </div>

        <div>
          <h2 className="text-2xl font-black">
            AI Recommendations
          </h2>

          <p className="text-slate-500 mt-1">
            Personalized suggestions generated by Skillora AI.
          </p>
        </div>

      </div>

      <div className="space-y-5">

        {displayRecommendations.map((item,index)=>(


          <div
            key={index}
            className="rounded-3xl border border-slate-200 p-6 hover:border-blue-300 transition"
          >

            <div className="flex justify-between">

              <div>

                <div className="flex gap-3 items-center mb-3">

                  <FaLightbulb className="text-yellow-500"/>

                  <h3 className="font-bold text-lg">
                    {item.title}
                  </h3>

                </div>

                <p className="text-slate-500 leading-7">
                  {item.description}
                </p>

              </div>

              <button className="text-blue-600">
                <FaArrowRight/>
              </button>

            </div>

          </div>

        ))}

      </div>

    </div>
  );
}

export default AIRecommendations;